title: My Portfolio
description: Cybersecurity Enthusiast | CTF Player | Web Enthusiat
baseurl: ""
url: "https://ameera-chan.github.io"

# Social media
github_username: ameera-chan
linkedin_username: https://www.linkedin.com/in/nur-ameera-chan-240a9a242/

# Build settings
markdown: kramdown
highlighter: rouge

# Custom styles
sass:
  style: compressed
  sass_dir: _sass
  sourcemap: never

# Plugins
plugins:
  - jekyll-sass-converter
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - _site
  - .github

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# GitHub Pages settings
github: [metadata]
theme: null
remote_theme: null
